export const VOCABULARY = {
  feelsLike: {
    eng: 'feels like',
    rus: 'ощущается как',
    bel: 'адчуваецца як',
  },
  wind: {
    eng: 'wind',
    rus: 'ветер',
    bel: 'вецер',
  },
  windSpeed: {
    eng: 'm/s',
    rus: 'м/с',
    bel: 'м/с',
  },
  humidity: {
    eng: 'humidity',
    rus: 'влажность',
    bel: 'вільготнасць',
  },
  latitude: {
    eng: 'Latitude',
    rus: 'Широта',
    bel: 'Шырыня',
  },
  longitude: {
    eng: 'Longitude',
    rus: 'Долгота',
    bel: 'Даўгата',
  },
  placeholder: {
    eng: 'Search place',
    rus: 'Найти место',
    bel: 'Знайсцi месца',
  },
  month: {
    eng: {
      January: 'January',
      February: 'February',
      March: 'March',
      April: 'April',
      May: 'May',
      June: 'June',
      July: 'July',
      August: 'August',
      September: 'September',
      October: 'October',
      November: 'November',
      December: 'December',
    },
    rus: {
      January: 'Января',
      February: 'Февраля',
      March: 'Марта',
      April: 'Апреля',
      May: 'Мая',
      June: 'Июня',
      July: 'Июля',
      August: 'Августа',
      September: 'Сентября',
      October: 'Октября',
      November: 'Ноября',
      December: 'Декабря',
    },
    bel: {
      January: 'Студзеня',
      February: 'Лютага',
      March: 'Сакавiка',
      April: 'Красавiка',
      May: 'Мая',
      June: 'Червеня',
      July: 'Лiпеня',
      August: 'Жнiўня',
      September: 'Верасня',
      October: 'Кастрычнiка',
      November: 'Лiстапада',
      December: 'Снежня',
    },
  },
  weekDay: {
    eng: {
      Mon: 'Mon',
      Tue: 'Tue',
      Wed: 'Wed',
      Thu: 'Thu',
      Fri: 'Fri',
      Sat: 'Sat',
      Sun: 'Sun',
    },
    rus: {
      Mon: 'Пнд',
      Tue: 'Вт',
      Wed: 'Ср',
      Thu: 'Чт',
      Fri: 'Пт',
      Sat: 'Сб',
      Sun: 'Вск',
    },
    bel: {
      Mon: 'Пнд',
      Tue: 'Аўт',
      Wed: 'Сер',
      Thu: 'Чцв',
      Fri: 'Пят',
      Sat: 'Суб',
      Sun: 'Няд',
    },
  },
  // error: {
  //   eng: 'Server response error',
  //   rus: 'Ошибка ответа сервера',
  //   bel: 'Памылка адказу сервера',
  // },
  // locationError: {
  //   eng: 'No such location',
  //   rus: 'Локация не обнаружена',
  //   bel: 'Месца не знойдзена',
  // },
};

export const ORDER_TO_WEEKDAY = {
  eng: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
  rus: ['понедельник', 'вторник', 'среда', 'четверг', 'пятница', 'суббота', 'воскресенье'],
  bel: ['панядзелак', 'аўторак', 'серада', 'чацьвер', 'пятнiца', 'субота', 'нядзеля'],
};
